module.exports = {
  py: 'python',
  js: 'javascript',
  cpp: 'c++',
  rb: 'ruby',
  ts: 'typescript',
  sh: 'bash',
  sql: 'sql database',
  sqlite: 'sqlite database',
  md: 'markdown',
  txt: 'plain text',
  ttf: 'truetype font',
  otf: 'opentype font',
  blend: 'blender',
  bas: 'qbasic',
  btm: 'batch',
  coffee: 'coffeescript',
  cs: 'c#',
  erb: 'ruby on rails',
  kt: 'kotlin',
  lol: 'lolcode',
  pl: 'perl',
  r: 'r lang',
  c: 'c lang',
  vbs: 'visual basic script',
  clj: 'clojure',
  d: 'd lang',
  el: 'emacs lisp',
  fth: 'forth',
  lisp: 'common lisp',
  scm: 'scheme',
  tmp: 'temporary file',
  bf: 'brainf***',
  ejs: 'embedded javascript'
}
